- drivers/tapdisk-control.c
When two tapdisk processes are spawned at the same time, they race
to create the /var/run/blktap-control directory. We currently don't handle
the error condition EEXIST where one tapdisk process finds that
the directory already exists.
Signed-off-by: Chandrika Srinivasan chandrika.srinivasan@citrix.com
> CA-222124: Handle race-condition in tap-ctl spawn

- drivers/tapdisk-control.c
Add delay in between attempts to pause the same vbd so that the syslog doesn't get hard spammed for no benefit
Signed-off-by: Mark Syms mark.syms@citrix.com
> CA-223652: Add delay to reduce number of syslog messages

- mk/Makefile
- mk/version.m4
From: Germano Percossi <germano.percossi@citrix.com>
- Version needs to be a pure numerical value
- patch queue info moved to Release section
- Removed XenServer version info from the specfile
Signed-off-by: Germano Percossi <germano.percossi@citrix.com>
> CP-19449: Fix Version and Release tag in specfile

- drivers/Makefile.am
- drivers/block-ntnx.c
- drivers/block-ntnx.h
- drivers/tapdisk-disktype.c
- drivers/tapdisk-disktype.h
This ntnx backend provides a 100% userspace datapath for tapdisk to access
storage on Nutanix hyperconverged appliances. It uses libfrodoiscsi.so, a
highly efficient library for iSCSI protocol handling and SCSI command
passthrough. The .so is shipped separately by Nutanix and is not part of
the tapdisk distribution. Therefore, tapdisk does not link with the .so
at build time and instead the ntnx backend dlopen()'s the .so at runtime.
block-ntnx.c, which connects tapdisk with libfrodoiscsi.so, is contributed
by Nutanix under the same 3-clause BSD license as rest of tapdisk.
Signed-off-by: Mike Cui <cui@nutanix.com>
Reviewed-by: Chandrika Srinivasan <chandrika.srinivasan@citrix.com>
> Introduce a new block backend called 'ntnx'

- drivers/scheduler.c
- drivers/scheduler.h
There are few events that persits throughout the life of
tapdisk process itself. Hence, when scheduler uuid overflow
occurs we should skip replacing these events for proper
functioning of tapdisk.
Signed-off-by: Sharath Babu sharath.babu@citrix.com
> CA-217394: Handle scheduler uuid data type overflow in tapdisk

- vhd/lib/vhd-util-coalesce.c
In 'vhd_util_coalesce_load_chain()', cleaning up in case of an
error is wrongly implemented.
Basically, we try to figure out if the object pointed to by 'entry'
has made its way into the list or not. Although the rationale for
doing that is not wrong per se (checking if its list was empty,
which it technically is, until it is added to one), it needed
something extra to work; its 'list_head' member initialized by calling
'INIT_LIST_HEAD(&entry->next)'. This had to be done for every newly
allocated object.
The approach we took here is a bit different. Instead of doing the
above, which would have worked fine, we check if the object pointed
to by 'entry' and the last object in the list live in the same
address. If yes, do not do anything, 'vhd_util_coalesce_free_chain()'
will free it. If no, …
> CP-18038: Fix multiple resource leaks

- vhd/lib/libvhd.c
In order to be able to open the VHD leaf with O_DSYNC
we now have a check for the existence of a file.
The file is /etc/tapdisk_use_dsync
If the file exists the option O_DSYNC is added to O_DIRECT.
This is not a public interface, but just an hardcoded debug
interface.
Signed-off-by: Stefano Panella <stefano.panella@citrix.com>
> Add a check to force O_DSYNC if needed

- misc/coverity/model.c
Use the asprintf model used by Xen in their coverity scan.
> Add coverity model.c to support asprintf

- control/tap-ctl-create.c
- control/tap-ctl-spawn.c
- control/tap-ctl.c
- include/tap-ctl.h
The '-c' option allows the user to specify which cgroup slice the new tapdisk
process should be put in. If unspecified, it is moved to the default cgroup
slice.
This avoids the need to rely on the cgrulesengd daemon which fails to do its job
if the time it takes to write to the tasks file exceeds the lifespan of the
parent tapdisk (before it forks and exits). On a 4.4 kernel, it can take several
milliseconds to write to this file, so that kind of failure is very likely.
Signed-off-by: Jonathan Davies jonathan.davies@citrix.com
> CA-225067: tap_ctl_{spawn,create}: move tapdisk to cgroup slice

- include/libvhd.h
- vhd/lib/libvhd-journal.c
- vhd/lib/libvhd.c
- vhd/lib/libvhdio.c
- vhd/lib/vhd-util-check.c
- vhd/lib/vhd-util-coalesce.c
- vhd/lib/vhd-util-read.c
- vhd/lib/vhd-util-scan.c
- retry open() with O_DSYNC if an EINVAL error was encountered
ZFS doesn't support O_DIRECT, so I adopted what I hope is the least intrusive changes to the codebase.
> make O_DIRECT optional

- tapback/backend.c
In rare cases tapback is asked to process a watch where the path in
xenstore has been deleted before the first notification. In this case
the logic could get confused and run on to call frontend() with a NULL
argument, causing frontend() to assert().
tapback_backend_probe_device() is documented to either create or remove
a device. If it finds itself doing neither, simply warn and return an
error.
> CA-299175: Deal with events on non-existent paths

- vhd/lib/vhd-util-fill.c
Also fix an off by one in the extents calculation for -b.
> CA-303671: initialise variable so that -B functions

- drivers/block-vhd.c
- vhd/lib/libvhd.c
> CA-304648: add guard asserts to prevent overwriting the header

- drivers/td-blkif.c
- drivers/td-req.c
It is possible for attempts to be made to access through
blkif->stats.xenvbd after the memory it points to has been unmapped by
calling tapdisk_xenblkif_stats_destroy().
NULL the pointer as the memory is unmapped and check it before each
use. If tapdisk_xenblkif_stats_destroy() has been called, we shouldn't
be interested in those updates any more anyway.
> CA-304562 Stats use-after-free

- vhd/lib/xattr.c
vhd_get_keyhash in libvhd.c uses xattr to retrieve a keyhash when the vhd does not have a batmap.
Since extended attributes is not supported for NFS SRs, using xattr_get in NFS SRs would previously cause a failure when trying to obtain the key from the filesystem.
This broke sr-scan when we had VDIs that were created by other tools.
This change handles this failure, so xattr_get returns 0 when extended attributes is not supported and there is no key to retrieve.
Signed-off-by: Elias Calocane <elias.calocane@citrix.com>
> CA-305951: change xattr_get to tolerate ENOTSUP error

- tapback/backend.c
So that we see successful calls as well as failures.
> CA-306397: amend tracing in physical_device_changed.

- tapback/backend.c
> CA-306397: consider empty string read from xs_read to be equiv to NULL

- vhd/lib/vhd-util-key.c
At present if the keypath doesn't contain '/' will result in a segfault.
Signed-off-by: Mahantesh Salimath <salimathm@ainfosec.com>
> fix vhd-util keypath validation

- drivers/block-vhd.c
- include/libvhd.h
- vhd/lib/vhd-util-copy.c
- vhd/lib/vhd-util-key.c
This PR consolidates the three definitions of LIBBLOCKCRYPTO_NAME into libvhd.h and adds the major version (.0) to the string.
OpenXT doesn't install a `libblockcrypto.so` symlink, only `libblockcrypto.so.0` as a symlink to `libblockcrypto.so.0.0.0`.  This leads to a runtime failure when dlopen can't find the library - "failed to load crypto support library".  It's more defensive to specify the major version.  That way a major version change will result in an error instead of being used when there can be incompatible changes.
`libblockcrypto.so` should already be a symlink to `libblockcrypto.so.0.0.0` anyway, so there should be no functional change.  I've tested this on OpenXT, but not XenServer.  On an existing XenServer system, you can verify the `libblockcrypto.so.0` is present to …
> LIBBLOCKCRYPTO_NAME consolidation & versioning

- drivers/td-blkif.c
- drivers/td-req.c
- drivers/td-req.h
- include/blktaplib.h
- include/xen_blkif.h
- tapback/backend.c
* Enable multipage ring support in blktap
* When in polling mode, mask the event channel events to reduce system call overhead.
> Blktap performance updates

- LICENSE
- drivers/Makefile.am
- drivers/aio_getevents.c
- drivers/aio_getevents.h
- drivers/tapdisk-queue.c
- include/spdk/barrier.h
- include/spdk/likely.h
- include/spdk/stdinc.h
- include/spdk/util.h
- vhd/lib/libvhd.c
This can be done entirely in user-space, which is how SPDK, FIO and QEMU does it.
To get the full speed improvements this also requires using `preadv` instead of `pread`, coming up in a separate PR.
A little more information about this can be found here:
https://blog.cloudflare.com/io_submit-the-epoll-alternative-youve-never-heard-about/#gettingridofio_getevents
> CA-327558: avoid io_getevents syscall and fadvise

- drivers/Makefile.am
- drivers/tapdisk-ring.c
- drivers/tapdisk-ring.h
- drivers/td-blkif.c
- drivers/td-blkif.h
- drivers/td-ctx.c
- drivers/td-ctx.h
- drivers/td-req.c
- drivers/td-req.h
- drivers/td-stats.c
- include/blktap-xenif.h
- include/blktaplib.h
- tests/test_td-ctx.c
- tests/test_td-req.c
libxenctl is not a stable interface. Instead of using it, we should use
libxenevtchn and libxengnttab which have stable sonames
Create a new include/blktap-xenif.h for the bits we need for the control
interfaces.
Use PAGE_SIZE rather than XC_PAGE_SIZE
> CP-32675 Use the stable Xen interfaces

- drivers/block-valve.c
tapdisks stats are finally parsed as JSON, and JSON does not
support hex literal.
Signed-off-by: Robin Lee <robinlee.sysu@gmail.com>
> valve: don't print stats in hex literal

- drivers/block-crypto.c
- drivers/block-crypto.h
- drivers/block-vhd.c
- drivers/crypto/compat-crypto-openssl.h
- drivers/crypto/xts_aes.c
- drivers/crypto/xts_aes.h
- mk/blktap.spec.in
This patch needs to be merged with blktap.spec together as CCM openssl
1.1.1 is required when building this package
Signed-off-by: Qin Zhang <qin.zhang@citrix.com>
> CP-32123: Integrate blktap with CCM openssl 1.1.1

- control/tap-ctl.c
> CA-335771: correct missing usage info

- control/tap-ctl.c
Also add timeouts to the usage of destroy and pause
which were previosuly undocumented.
> CA-335771: timeouts are deltas not absolute deadlines

- vhd/lib/vhd-util-scan.c
Currently vhd-util supports the wildcard pattern: 
```vhd-util scan -f -m "VHD-*" ...```
I would like to support pattern list to avoid many vhd-util calls like:
```
./vhd/vhd-util scan -f -m "{/dev/VG_XenStorage-f1f91902-e20e-41ee-fac0-5fa4bc71d0cf/VHD-,/root/vhd-backups/}*"
vhd=VHD-53941576-8955-42f6-bb54-98ea972bb639 capacity=53687091200 size=0 hidden=0 parent=none
vhd= d49cd80a-61ef-11ea-bc55-0242ac130003.vhd capacity=53687091200 size=0 hidden=0 parent=none
```
This PR add this functionality without breaking the default vhd-util command line. And it fixes a bad comparison to `FNM_PATHNAME` in another commit.
> feat(vhd-util-scan): '-m' supports style brace expressions and pattern list

- mockatests/control/Makefile.am
- mockatests/control/control-wrappers.c
- mockatests/control/control-wrappers.h
- mockatests/control/test-control.c
- mockatests/control/test-suites.h
- mockatests/control/test-tap-ctl-allocate.c
- mockatests/control/test-tap-ctl-free.c
Refine mock enablement/disablement into setup & teardown
> Add unit tests for tap-ctl allocate

- cbt/cbt-util.c
Compiling with -Og flags this property as potentially being used without initialisation.
> Fix compilation error when compiling with -Og

- control/tap-ctl-list.c
- mockatests/control/Makefile.am
- mockatests/control/control-wrappers.c
- mockatests/control/test-control.c
- mockatests/control/test-suites.h
- mockatests/control/test-tap-ctl-close.c
- mockatests/control/test-tap-ctl-list.c
- mockatests/control/util.c
- mockatests/control/util.h
Fix regression bug in listing allocated but not attached tapdisk device minor ids, introduced in a kernel patch change in 2014.
> Add unit tests for tap-ctl list

- drivers/tapdisk-metrics.c
- drivers/td-req.c
> CA-338080: prevent segfault if stats have been freed

- misc/coverity/model.c
- vhd/lib/vhd-util-copy.c
Update coverity model
Works around Coverity bug - https://community.synopsys.com/s/article/From-Case-how-to-suppress-NULL-RETURNS-on-errno-location
> CA-338176: fix resource leaks in vhd-util copy

- configure.ac
- mockatests/Makefile.am
- mockatests/vhd/Makefile.am
- mockatests/vhd/test-suites.h
- mockatests/vhd/test-vhd-util-snapshot.c
- mockatests/vhd/test-vhd-util.c
- mockatests/vhd/vhd-wrappers.c
- mockatests/vhd/vhd-wrappers.h
- vhd/lib/vhd-util-snapshot.c
propagating the errors allows SM to fail gracefully.
Waiting for a build to complete and then I can run this through a BST and remove the red label.
> CA-340619 - Propagate error froms from snaphot creation

- mockatests/vhd/test-vhd-util-snapshot.c
- vhd/lib/vhd-util-snapshot.c
Also address 
* CA-342578: switch case fall through in vhd-util snapshot (identified by Coverity and tripped in the unit tests)
> CA-342553: Fix vhd-snapshot with raw parent

- control/tap-ctl-create.c
- control/tap-ctl-spawn.c
- control/tap-ctl.c
- include/tap-ctl.h
Revert "CA-225067: tap_ctl_{spawn,create}: move tapdisk to cgroup slice"
This reverts commit ce3df05d75310f130928e391fe17e7755809dd42.
Signed-off-by: ben sims <ben.sims@citrix.com>
> CP-32988 - Remove cgroup manipulation from tap-ctl.

- include/libvhd.h
- vhd/lib/libvhd.c
The function whilst unused in blktap is used in third-party library
consumers.
This reverts commit 62158e24fa12f4f840b118d5c523a78cdd3189be.
> Revert "CP-34908: Remove dead write_block function"

- vhd/lib/canonpath.c
- vhd/lib/libvhd.c
Preserve symlinks when "/dev/drbd/by-res/<RES_NAME>/<VOLUME>" paths are used.
It's interesting when a parent is set to a VHD file to avoid usage of
"/dev/drbdXXXX" paths where XXXX is the device minor number.
We can have:
>\> vhd-util query -n /dev/drbd/by-res/volume-d803817e-6113-4b89-abdf-d4ab39d63e8c/0 -p
/dev/drbd/by-res/volume-d5f5a079-0529-4b97-95be-9a859056d523/0
instead of:
>\> vhd-util query -n /dev/drbd/by-res/volume-d803817e-6113-4b89-abdf-d4ab39d63e8c/0 -p
/dev/drbd/./drbd1004
If a DRBD resource exists on many hosts with a resource name equal to an UUID, it can be used
independently of the DRBD device minor number on each host.
Signed-off-by: Ronan Abhamon <ronan.abhamon@vates.fr>
> feat(vhd/canonpath): add support for DRBD resource path

- cpumond/Makefile.am
- cpumond/cpumond.c
> CA-344424: ensure we don't get division by 0

- vhd/lib/canonpath.c
> CA-345193: allocate sufficient space in normalize_path

- .gitignore
- collect-test-results.sh
- mockatests/vhd/Makefile.am
- mockatests/vhd/test-canonpath.c
- mockatests/vhd/test-suites.h
- mockatests/vhd/test-vhd-util-snapshot.c
- mockatests/vhd/vhd-wrappers.c
- mockatests/vhd/vhd-wrappers.h
If the fix in https://github.com/xapi-project/blktap/pull/335 is reverted in the presence of this unit test it will correctly fail with a buffer overrun error.
> Add a unit test for canonpath that exercises the code affected by CA-345193

- vhd/lib/vhd-util-check.c
> CA-349971: use correct return type for memcmp

- drivers/Makefile.am
- drivers/block-nbd.c
- drivers/block-vhd.c
- drivers/tapdisk-image.c
- drivers/tapdisk-interface.c
- drivers/tapdisk-interface.h
- drivers/tapdisk-nbdserver.c
- drivers/tapdisk-nbdserver.h
- drivers/tapdisk-protocol-new.h
- drivers/tapdisk-vbd.c
- drivers/tapdisk-vbd.h
- drivers/tapdisk.h
- mockatests/drivers/Makefile.am
- mockatests/drivers/test-drivers.c
- mockatests/drivers/test-tapdisk-nbdserver.c
- mockatests/drivers/test-tapdisk-vbd.c
- mockatests/drivers/vbd-wrappers.c
This commit implements a minimal set of options for CH use cases. The following scenarios have been tested.
1) blktap -> blktap (SXM)
2) blktap -> qemu (VM boot)
3) blktap -> nbclient (vdi-copy)
4) blktap -> python-nbd-client (sparse-dd)
Unfortunately, we need to maintain the old handshake for SXM backwards compatibility. Thus the new protocol is
deactivated by default pending tap-ctl changes to toggle handshake protocol.
This has been passed through the storage BST twice both with new and old protocols.
Suite run 141670 -> New protocol turned on.
Suite run 141696 -> New protocol turned off.
> CP-35115 - New fixed style nbd option negotiation.

- drivers/io-backend.h
- drivers/libaio-backend.c
- drivers/posixaio-backend.c
Running this through a BST. I will remove the do not merge if reviewers are happy and the BST succeeds.
I used a union to avoid the malloc and void* (Coverity complained that the malloc could fail and we'd have a NULL pointer) Propagating a failure in malloc would have meant changing function interfaces in many files and very error prone.
> CA-35250 - Fix Coverity issues introduced by CP-32853

- drivers/blktap
Commit c4a722c3da47 ("CA-153279: don't complain if there's no tapdisk to
signal") made killall quiet if there are no tapdisks to signal during
logrotation. However, it stills exits with non-zero in this case which
makes logrotate complain to dead.letter:
error: error running shared postrotate script for '/var/log/blktap/tapdisk.*.log '
Instead, always return success.
Signed-off-by: Ross Lagerwall ross.lagerwall@citrix.com
> CA-183182: Don't error if there are no tapdisks to signal

- drivers/tapdisk-server.c
The POSIX AIO backend has some issues. While addressing them it would be good
to make some other alterations as well, so for now just redirect to the libaio
backend.
> CA-353265 Disable posix AIO backend

- drivers/tapdisk-server.c
> CA-356180: ensure queue is valid before debug dumping it

- LICENSE
> Correct typo in LICENSE file and remove obsolete files

- control/tap-ctl-allocate.c
- drivers/tapdisk-blktap.c
- vhd/lib/libvhd.c
glibc moved the declarations of major, minor and makedev from
sys/types.h to sys/sysmacros.h, so make the change.  sys/types.h is left
for backwards compatibility.  Fixes:
libvhd.c:144:9: error: implicit declaration of function 'makedev' [-Werror=implicit-function-declaration]
libvhd.c:156:33: error: implicit declaration of function 'major' [-Werror=implicit-function-declaration]
libvhd.c:172:64: error: implicit declaration of function 'minor' [-Werror=implicit-function-declaration]
Signed-off-by: Jason Andryuk <jandryuk@gmail.com>
> include sys/sysmacros.h

- drivers/Makefile.am
- drivers/prune_tapdisk_logs
- mk/blktap.spec.in
Whilst tapdisk primarily logs via syslog and into daemon.log it also
creates logs in /var/log/blktap, which are rotated imperfectly due to
the filename having the process id in it. This can result in a build
up of very old log files taking significant space in the log partition
which will not be freed by the standard logrotate mechanism. Remove
any files not modified in the last month.
> CA-366614: clean up old tapdisk log files

- control/tap-ctl-ipc.c
- control/tap-ctl-unpause.c
- control/tap-ctl-xen.c
- drivers/block-crypto.c
- drivers/block-nbd.c
- drivers/block-valve.c
- drivers/tapdisk-control.c
- drivers/tapdisk-disktype.c
- drivers/tapdisk-nbdserver.c
- drivers/tapdisk-stats.c
- drivers/td-rated.c
- include/util.h
- lvm/Makefile.am
- lvm/lvm-util.c
- vhd/lib/canonpath.c
- vhd/lib/canonpath.h
- vhd/lib/libvhd-index.c
- vhd/lib/libvhd.c
- vhd/lib/relative-path.c
- vhd/lib/vhd-util-coalesce.c
- vhd/lib/vhd-util-scan.c
- vhd/lib/vhd-util-snapshot.c
- vhd/vhd-index.c
Coverity 2021.12.1 adds complaints about strcpy and sprintf, so fix them.
> Fix a block of newly detected Coverity issues

- drivers/block-vhd.c
Coverity worries that bits will be lost before the uint32_t is extended to the uint64_t context. This will not happen, but keep Coverity happy.
> CA-365301 coverity: extend before left-shift

- include/blktap-xenif.h
mfence is overly heavyweight.  See:
https://xenbits.xen.org/gitweb/?p=xen.git;a=commitdiff;h=de16a8fa0db7f1879442cf9cfe865eb2e9d98e6d
for full details.
Signed-off-by: Andrew Cooper <andrew.cooper3@citrix.com>
> Relax xen_mb() from mfence to a locked instruction

- cpumond/cpumond.c
- drivers/block-vhd.c
- drivers/tapdisk-blktap.c
- drivers/tapdisk-control.c
- drivers/tapdisk-utils.c
- drivers/tapdisk-utils.h
- drivers/tapdisk-vbd.c
- drivers/tapdisk-vbd.h
- drivers/td-blkif.c
- drivers/td-blkif.h
- drivers/td-req.c
- mockatests/wrappers/wrappers.c
- vhd/lib/vhd-util-copy.c
- vhd/lib/vhd-util-key.c
- vhd/lib/vhd-util-read.c
This series is assorted compilation fixes for GCC 11.2 (Fedora 35).
> GCC 11.2 compile fixes

- mockatests/cbt/Makefile.am
- mockatests/wrappers/Makefile.am
- mockatests/wrappers/wrappers.c
The devtoolset-11 compiler, when run with -O2 on the product code replaced a `malloc` + `memset` with a call to `calloc`, which then reported memory corruption errors when trying to use the `free` function from the mocka allocator library.
> Make CBT Mocka tests work properly with devtoolset-11

- drivers/tapdisk-nbdserver.c
- drivers/tapdisk-nbdserver.h
Found by `gcc -fanalyzer`, most others look like false positives due to use of kernel style linked list handling
> Fix use after free in NBD server

- include/util.h
The stringop-truncation warning will fire when there is an attempt to strncpy N characters into a destination string of length N, including the null character. The safe_strncpy() function does this for us by copying N characters and truncating at length N-1, but the previous strncpy() call is technically "incorrect" as GCC sees it. Reduce the sz by one to resolve these warnings. This behavior should be functionally equivalent to the original.
> Silence GCC stringop-truncation warnings

- include/libvhd.h
- vhd/lib/libvhd.c
- vhd/lib/vhd-util-coalesce.c
Reduce the amount of data read during coalesce. Especially, do not read up the chain of parents when all that is required is the allocation block from the current VHD.
> CP-37221: Optimise data management in vhd-util coalesce

- drivers/block-vhd.c
- drivers/tapdisk-vbd.c
Rationalise the IO error handling in the block handlers. In a scenario where the NFS server connection has dropped the retires can add up to an extremely large amount of time being spent before the IO requests are failed back to the VM.
> Rationalise blktap io errors

- control/tap-ctl.c
tap-ctl list is returning the allocated but unattached tapdevs when used with -t and -f.  We want to skip those since they don't match.
Full output:
$ tap-ctl list
334529    1    0        vhd /home/user/test.vhd
334534    2    0        aio /home/user/test.aio
-    0    -          - -
Filtered before this change:
$ tap-ctl list -t vhd -f /home/user/test.vhd
334529    1    0        vhd /home/user/test.vhd
-    0    -          - -
Filtered after this change:
$ tap-ctl list -t vhd -f /home/user/test.vhd
334529    1    0        vhd /home/user/test.vhd
> tap-clt: Improve list output filtering

- drivers/tapdisk-vbd.c
When the tapdisk-vbd layer receives a request to forward an IO request it checks if the VBD queue is ready. If it not ready, either being quiesced or less likely is already quiesced, it fails the request with EBUSY to allow the entire request to be retired later. When doing so it directly calls its own internal completion function and does not notify the forwarding driver of the status which might result in that driver still believing the request to be in progress when it is asked to close.
> CP-46763: When VBD queue is not ready call the driver completion

- drivers/tapdisk-vbd.c
Use one point of assessment of outstanding work queues to issue requests into the driver layer for consitency and ensuring a common set of criteria are applied to which requests to forward.
> CP-46778: always issue request via issue_requests

- cbt/Makefile.am
In recent toolchain versions having the -l options before the .la file results in the exported functions in the libraries not being seen by the linker if LTO is disabled.
> Fix the order of linker options in CBT

- drivers/block-valve.c
After tapdisk-vbd forwards a td_request_t to the next driver layer that driver is at liberty to decompose the request into smaller sub-requests, e.g. to accomodate spanning a VHD allocation block boundary. If this occurs, the individual sub-requests will complete independently and call the request callback in the higher driver layer.
The callback handler in block-valve, `__valve_complete_treq` does not correctly handle the condition if an intermediate request completes with an error but the final request which decrements the outstanding sector count to 0 suceeds. This results in a completion being sent to the next layer up the stack reporting that the entire IO request is complete when actually it is not and thus at some point later the guest VM will detect corruption to its disk …
> CA-384162: Send completions for all partial responses

- control/tap-ctl-allocate.c
- control/tap-ctl-check.c
- drivers/block-vhd.c
- drivers/tapdisk-control.c
- drivers/tapdisk-diff.c
- drivers/tapdisk-image.c
- drivers/tapdisk-stream.c
- drivers/tapdisk-vbd.c
- drivers/tapdisk-vbd.h
- vhd/lib/vhd-util-read.c
- vhd/lib/vhd-util-scan.c
As we do `fscanf(f, "%d %32s", &minor, name)` we need a 33 char buffer
> Fix various memory management issues

- drivers/Makefile.am
Blktap has been updated to only use the stable, modern APIs and so no longer needs to request compat APIs.
> Remove no longer required xen API overrides

- drivers/tapdisk-nbdserver.c
When nbd server receives disconnect request from client, it frees
client data structure but it does not close the connection, then
it sends VDI size to client, the send most likely returns err as
client fd has been closed. However, in some case like half close,
send returns successfully, and then server will always keep this
opened fd in memory and never close it, finally, the number of
opened fd exceeds ulimit settings.
> CA-391882: fix nbd connection fd leak bug

- drivers/tapdisk-nbdserver.c
If the initial NBD server identification is sent, the NBD server registers a callback for events on the filedescriptor and awaits further activity. When this occurs after an NBD_CLOSE, as we allow a connection to be re-used for a new session, we must make sure to close the filedescriptor if the session is NOT re-used.
A previous fix plugged an FD leak which occurred when the NBDMAGIC failed to be sent fully at session initialisation. However, there is another leak which can occur when the NBDMAGIC is send, but not read, and the client closes the connection during the callback-driven phase of option negotiation.
Close that FD here whenever option negotiation fails.
Also, when there is an error during client communication which results in a client shutdown, the FD needs to be closed there …
> CA-401174 Filedescriptor leak in NBD option negotiation

- drivers/block-lcache.c
- drivers/tapdisk-vbd.c
- drivers/tapdisk.h
When the lcache driver has read from the remote storage and returned the data to the caller it then stores the data into the local vhdcache by forwarding a write to the vhdcache file. As the vhdcache file is opened in TD_VBD_SECONDARY_MIRROR mode this also results in the data being unnecessarily written back to the remote where it has just been read from.
> CA-403297: when storing read-through do not mirror

- include/libvhd.h
- vhd/lib/libvhd.c
- vhd/lib/vhd-util-query.c
Add the ability to vhd-util to find the parent of a VHD without locally resolving or calling stat on the locator path.
A cmdline option `-u` (unresolved) is now available to query the parent path without resolution.
Use cases:
- When a special SR driver is used where the parent is not always accessible on the master (DRBD case).
- A copy of a VHD on an external device without parent
- ...
Example:
```
vhd-util query -u -n /dev/drbd/by-res/xcp-volume-1d86819f-c844-4250-8f3a-df5de9227baa/0 -p
../xcp-volume-56c6ef19-3d87-4838-b5e6-9c534bc1a0cb/0
```
> Add an option to never resolve parent path when vhd-util query is called

- cbt/Makefile.am
- collect-test-results.sh
- control/Makefile.am
- cpumond/Makefile.am
- drivers/Makefile.am
- lvm/Makefile.am
- mockatests/cbt/Makefile.am
- mockatests/control/Makefile.am
- mockatests/drivers/Makefile.am
- mockatests/vhd/Makefile.am
- tapback/Makefile.am
- vhd/Makefile.am
- vhd/lib/Makefile.am
Directing the profile-dir to an out of tree location results in gcc 12 creating paths with the separators of the absolute source path converted to # characters. When subsequently using gcov or lcov to analyse the coverage this produces errors and no coverage data is produced. As the collect-test-results.sh pulls these files back into the build tree and published them from there it isn't necessary to write them elsewhere and this avoids the decorated paths being created.
> CA-387574: Fix build time coverage gathering

- collect-test-results.sh
The previous change 8c5bb7d, inadvertently omitted a number of 0% coverage files, presenting a misleading report of coverage. Rectify that by calling lcov with a --initial.
> CA-387574: Get coverage for all files

- drivers/tapdisk-interface.c
- drivers/tapdisk-vbd.c
In cases where a request cannot be dispatched because a driver doesn't implement the target function log the error before returing the error code.
Additionally log the image name when processing a failure in td_complete_request.
> CP-54256: log errors when reporting EOPNOTSUP

- drivers/tapdisk-server.c
Low memory monitoring and CPU usage monitoring are used for different purposes: if we fail to initialize one, we should still try to initialize the other.
Low memory monitoring is used to reduce queue depth / buffers allocated when we have a lot of disks attached on the same host.
CPU usage monitoring is used to determine when it is safe to enter busy polling mode: when Dom0 is already under high load then we don't enter busy polling mode to allow other processes to use the CPU. If CPU usage monitoring is not initialized then tapdisk never enter polling mode, which reduces guest I/O performance.
Low memory monitoring currently fails to initialize with a newer kernel CA-400404, which exposed this latent performance bug in tapdisk. We should fix lowmem mode, but for now fix the performance …
> CA-414626: initialize cpumon even if lowmem initialization failed

- drivers/td-req.c
Returning BLKIF_RSP_ERROR if an operation is not supoprted does not allow the frontend to exercise any discretion on how to handle the response and may lead to an operating system crash. As different backends may support different feature sets and we might, during a migration, switch backends, an in-flight request might be issued (or reissued) which is then not supported by this backend.
> CA-416464: return BLKIF_RSP_EOPNOTSUPP for EOPNOTSUPP
