xapi-project/blktap

- drivers/tapdisk-control.c
tap-ctl close accepts a force flag but it is not considered
by tapdisk while closing the image. With this change, tapdisk
will ignore pending I/Os on dead rings when asked to close an
image in "force shutdown" mode
> CA-227162: Enable tapdisk forced shutdown mode

- tapback/tapback.c
Signed-off-by: Sharath Babu <sharath.babu@citrix.com>
Reviewed-by: Mark Syms <mark.syms@citrix.com>
> CA-220042: sigact.sa_mask is not initialized (CID:57552)

- vhd/lib/libvhd.c
Signed-off-by: Mark Syms mark.syms@citrix.com
> CA-221904: vhd create EINVAL, report errors

- vhd/lib/libvhd.c
Signed-off-by: Gary Kirkpatrick <gary.kirkpatrick@citrix.com>
> CA-220608: Corrected coverity warnings

- mk/blktap.spec.in
> Update specfile template

- vhd/lib/libvhd.c
Signed-off-by: Elias Calocane <elias.calocane@citrix.com>
> CP-24318: Closed resource leak in vhd_macx_decode_location()

- cbt/Makefile.am
- collect-test-results.sh
- control/Makefile.am
- cpumond/Makefile.am
- drivers/Makefile.am
- lvm/Makefile.am
- mockatests/cbt/Makefile.am
- mockatests/drivers/Makefile.am
- tapback/Makefile.am
- vhd/Makefile.am
- vhd/lib/Makefile.am
> Update coverage profile dirs so that product and test code match

- drivers/block-nbd.c
When a filedescriptor is passed with a name, the name and fd are stored
in a free slot and later looked up by name. This means that if ever a
new fd is passed for a name, it will be invisible as the retriever will
return fd stored against the first matching name, which will be the
first instance.
To fix this, allow passed fds to overwrite the fd stored against an
existing name with the new fd.
Also, the current time was stored against each entry, but this is never
used so remove it. And correct the spelling of
tdnbd_retrieve_passed_fd()
> CA-227096 Allow stashed passed fds to overwrite with the same name

- control/tap-ctl-allocate.c
> CA-295527: more logging for tap-ctl allocate failures

- .gitignore
> Add more things to .gitignore

- drivers/block-nbd.c
- drivers/tapdisk-vbd.c
- vhd/lib/libvhd-journal.c
- vhd/lib/libvhd.c
Bulk change of a series of issues found by coverity.
I think they're mostly straightforward but please take a careful look and then we need to run some extensive tests.
> Fix coverity issues

- drivers/tapdisk-control.c
> Address coverity issues in tapdisk-control.c

- tapback/backend.c
We can be sent a notification for a device which has been removed. We
need to guard against this to prevent assertions, but cannot insist that
at least one of (create or remove) is true because there is additional
state-change behaviour.
Update the comments and add a check for device to prevent assertions.
> CA-299175 Guard against NULL devices

- vhd/lib/vhd-util-copy.c
> CA-303668: check that both name and new name are passed to vhd-util copy

- drivers/block-vhd.c
Previously we always loaded the crypto library when it was present, even
when we did not use encryption. This resulted in increased memory usage
for tapdisk - it used 8MB instead of 4MB.
Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>
> CA-304945: Only load crypto library when encryption is used

- mockatests/cbt/test-cbt-util-get.c
- mockatests/wrappers/wrappers.c
> Fix coverity issues in tests

- control/tap-ctl-allocate.c
> CA-310477: fix race in create tap-ctl directory

- vhd/lib/libvhd.c
> CA-312256: remove extraneous tracing from libvhd

- vhd/lib/libvhd.c
When allocating a new block we are about to fill entirely, avoid the
extra write to fill it with zeros first.
> Optimise allocate-and-fill of full blocks

- drivers/block-nbd.c
- drivers/tapdisk-nbdserver.c
> CA-320241: remove NBD mirror timeouts, they just add fragility

- control/tap-ctl-spawn.c
This will be useful to prioritize general dom0 IO ahead of IO from VMs.
> CP-27247: Move tapdisk to a blkio cgroup

- tapback/tapback.service
> CA-318654: set dependency on xenstored

- drivers/tapdisk-queue.c
This can return negative numbers on error, and that can result in very
unexpected behaviour.
> CA-326370 Check return code from io_getevents()

- .gitignore
- collect-test-results.sh
- configure.ac
- mockatests/Makefile.am
- mockatests/control/Makefile.am
- mockatests/control/control-wrappers.c
- mockatests/control/control-wrappers.h
- mockatests/control/test-control.c
- mockatests/control/test-suites.h
- mockatests/control/test-tap-ctl-free.c
- mockatests/wrappers/wrappers.c
Initial set only, more to follow.
> Add some unit tests for tap-ctl

- mockatests/control/Makefile.am
- mockatests/control/control-wrappers.c
- mockatests/control/control-wrappers.h
- mockatests/control/test-control.c
- mockatests/control/test-suites.h
- mockatests/control/test-tap-ctl-allocate.c
- mockatests/control/test-tap-ctl-close.c
> Add unit tests for tap-ctl close

- drivers/tapdisk-control.c
> CA-338603: fix out of band write in tapdisk-control

- mockatests/control/Makefile.am
> Remove direct reference to .libs directory

- control/tap-ctl-spawn.c
> CP-34900: remove command lookup by environment

- include/libvhd.h
- vhd/lib/libvhd.c
> CP-34908: Remove dead write_block function

- vhd/lib/libvhd.c
> CA-344119: return correct error, snprintf doesn't set errno

- drivers/tapdisk-fdreceiver.c
- drivers/tapdisk-nbdserver.c
> CA-350001: Check fds are valid before assigning

- vhd/lib/vhd-util-modify.c
> CA-350300: remove duplicated and unchecked call to canonpath

- drivers/tapdisk-server.c
- drivers/td-req.c
> CA-355145: guard vbd_stats

- control/tap-ctl-ipc.c
- drivers/tapdisk-control.c
> CA-356508: handle EINTR in tap-ctl IPC

- drivers/tapdisk-disktype.c
> CA-366761: fix off by one in tapdisk_disktype_parse_params

- drivers/tapdisk-utils.c
- drivers/tapdisk-utils.h
- mockatests/wrappers/wrappers.c
Two small follow ups to https://github.com/xapi-project/blktap/pull/357
> Small fixes

- drivers/tapdisk-vbd.c
Only check for new requests if the VBD request queues are not quiesced or in the process of being quiesced.
> CP-46771: separate queue checks for completed and new requests.

- drivers/block-vhd.c
In the possible event that there were no available vhd_request available it was possible that the operation would be failed having marked the BAT as locked with no attempt to unwind that lock. As it happens unwinding the lock could potentially be difficult as it is permitted for multiple requests which are updating the same newly created allocation block to be submitted so, just because the VHD_FLAG_REQ_UPDATE_BAT flag is set it is not certain that this request was the first to lock. To simplify this, first acquire the vhd_request which has simple cleanup if it fails, then acquire the BAT lock and release the vhd_request if this fails.
> CA-390490: allocate vhd request before locking bat

- mockatests/drivers/Makefile.am
- mockatests/drivers/test-drivers.c
- mockatests/drivers/test-scheduler.c
- mockatests/drivers/test-suites.h
New unit tests for `drivers/scheduler.c`.
Koji job: 657827
> CP-48057: Add unit tests for drivers/scheduler.c

- drivers/tapdisk-nbdserver.h
- mockatests/cbt/Makefile.am
- mockatests/cbt/test-cbt-util-set.c
- mockatests/control/Makefile.am
- mockatests/control/test-suites.h
- mockatests/control/test-tap-ctl-allocate.c
- mockatests/drivers/Makefile.am
- mockatests/drivers/test-scheduler.c
- mockatests/drivers/test-tapdisk-vbd.c
- mockatests/vhd/Makefile.am
Fix address sanitizer issues in unit tests.
> CP-46765 - Fix asan issues in unit tests

- drivers/tapdisk-nbdserver.c
The new fix has passed several rounds of internal testing, so should be good.
> Revert previous attempt and fix FD leak in NBD server

- drivers/tapdisk-nbdserver.c
Re-revert commit 9e7787c after a merge from before it was reverted put some of it back.
> Re-revert 9e7787c

- drivers/tapdisk-nbdserver.c
Previously the client was being enabled as part of
`tapdisk_nbdserver_newclient_fd_new_fixed` after calling
`tapdisk_nbdserver_new_protocol_handshake`. This erroneously assumed
that protocol handshake was complete by the time that function
returned, which is not the case as it simply adds the fd to an event
for the scheduler. Protocol handshake is only complete when we reach
the end of the `tapdisk_nbdserver_handshake_cb` callback and enabling
the client before this means we have two events registered for the
same fd.
This was causing quicktest to fail after blktap2 was removed and NBD
is used for all control domain access to the I/O datapath.
> CA-404370: enable NBD client only after completing handshake
